[package]
name = "elden-ring-msgs"
version = "0.1.0"
authors = ["Noiob <noiob@trillian.local>"]

[dependencies]
rand = "0.8.3"
elefren = { version = "0.22", features = ["toml"] }
serde = "1.0.123"
serde_json = "1.0.62"
